# Generated by Django 5.2.13 on 2026-05-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
